<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zeroone.star</groupId>
        <artifactId>psi-java</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>psi-sample</artifactId>
    <dependencies>
        <!-- spring mvc -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- 系统内置模块 -->
        <!-- common -->
        <dependency>
            <groupId>com.zeroone.star</groupId>
            <artifactId>psi-common</artifactId>
        </dependency>
        <!-- apis -->
        <dependency>
            <groupId>com.zeroone.star</groupId>
            <artifactId>psi-apis</artifactId>
        </dependency>
        <!-- nacos  -->
        <!-- alibaba nacos discovery -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <!-- alibaba nacos config -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <!-- 数据库相关  -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>
        <!-- druid -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.zeroone.star.sample.SampleApplication</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.zeroone.star</groupId>
                <artifactId>mp-code-generator-plugin</artifactId>
                <configuration>
                    <!-- 数据库连接信息配置 -->
                    <dbConfig>
                        <!-- 数据库主机地址 -->
                        <host>192.168.64.3</host>
                        <!-- 数据库端口 -->
                        <port>3306</port>
                        <!-- 数据库名称 -->
                        <dbname>test</dbname>
                        <!-- 数据库用户名 -->
                        <username>root</username>
                        <!-- 数据库密码 -->
                        <password>@Wen6603688</password>
                    </dbConfig>
                    <!-- 生成代码输出根目录 -->
                    <outDir>${project.basedir}/src/main/java</outDir>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
